//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bnetlauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bnetlauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [wow]
        ///name=World of Warcraft
        ///client=battlenet
        ///cmd=WoW
        ///exe=Wow.exe
        ///
        ///[d3]
        ///name=Diablo 3
        ///client=battlenet
        ///cmd=D3
        ///exe=Diablo III%.exe
        ///
        ///[hs]
        ///name=Hearthstone
        ///client=battlenet
        ///cmd=WTCG
        ///exe=Hearthstone.exe
        ///
        ///[ow]
        ///name=Overwatch
        ///client=battlenet
        ///cmd=Pro
        ///exe=Overwatch.exe
        ///
        ///[scr]
        ///name=Starcraft Remastered
        ///client=battlenet
        ///cmd=S1
        ///exe=StarCraft.exe
        ///
        ///[sc2]
        ///name=Starcraft 2
        ///client=battlenet
        ///cmd=S2
        ///exe=SC2Switcher%.exe
        ///
        ///[hots]
        ///name=Heroes of the Storm
        ///client=battlenet
        ///cmd=Hero
        ///exe=He [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gamesdb {
            get {
                return ResourceManager.GetString("gamesdb", resourceCulture);
            }
        }
    }
}
